export const UPDATE_TERM = "UPDATE_TERM";
export const JUMP_OUTPUT_CURSOR = "JUMP_OUTPUT_CURSOR";
export const HIGHLIGHT_OUTPUT_ITEM = "HIGHLIGHT_OUTPUT_ITEM";
export const RESULT_ITEM_UPDATED = "RESULT_ITEM_UPDATED";

export const SHOW_RESULT = "SHOW_RESULT";
export const SHOW_MAGIC_FILTER_SUGGESTION = "SHOW_MAGIC_FILTER_SUGGESTION";
export const HIDE_MAGIC_FILTER_SUGGESTION = "HIDE_MAGIC_FILTER_SUGGESTION";
export const HIGHLIGHT_MAGIC_FILTER_SUGGESTION_ITEM = "HIGHLIGHT_MAGIC_FILTER_SUGGESTION_ITEM";
export const ADD_MAGIC_FILTER = "ADD_MAGIC_FILTER";
export const HIDE_RESULT = "HIDE_RESULT";
export const UPDATE_RESULT = "UPDATE_RESULT";

export const PLUGIN_SUGGESTION_STARTED = "PLUGIN_SUGGESTION_STARTED";
export const PLUGIN_SUGGESTION_FINISHED = "PLUGIN_SUGGESTION_FINISHED";

export const PLUGIN_SEARCH_STARTED = "PLUGIN_SEARCH_STARTED";
export const PLUGIN_SEARCH_FINISHED = "PLUGIN_SEARCH_FINISHED";
export const PLUGIN_SEARCH_ENDED_WITH_ERROR = "PLUGIN_SEARCH_ENDED_WITH_ERROR";

export const SHOW_AUTOCOMPLETE = "SHOW_AUTOCOMPLETE";

export const SHOW_SUGGESTION = "SHOW_SUGGESTION";
export const HIDE_SUGGESTION = "HIDE_SUGGESTION";
export const HOVER_SUGGESTION = "HOVER_SUGGESTION";
export const MOUSE_OUT_SUGGESTION = "MOUSE_OUT_SUGGESTION";
export const REFRESHING_SUGGESTION = "REFRESHING_SUGGESTION";

export const RESET = "RESET";

export const ICON_LOADED = "ICON_LOADED";

export const SET_STATUS_BAR_TEXT = "SET_STATUS_BAR_TEXT";

export const AUTH_STATE_CHANGED = "AUTH_STATE_CHANGED";
export const TOKENS_CHANGED = "TOKENS_CHANGED";
export const START_AUTHENTICATING = "START_AUTHENTICATING";

export const FETCHING_AVAILABLE_APPS_LIST = "FETCHING_AVAILABLE_APPS_LIST";
export const FETCHING_AVAILABLE_APPS_LIST_SUCCESS = "FETCHING_AVAILABLE_APPS_LIST_SUCCESS";
export const FETCHING_AVAILABLE_APPS_LIST_ERROR = "FETCHING_AVAILABLE_APPS_LIST_ERROR";

export const FETCHING_CONNECTS_LIST = "FETCHING_CONNECTS_LIST";
export const FETCHING_CONNECTS_LIST_SUCCESS = "FETCHING_CONNECTS_LIST_SUCCESS";
export const FETCHING_CONNECTS_LIST_ERROR = "FETCHING_CONNECTS_LIST_ERROR";

export const CONNECT_APP_AUTH_CODE_RECEIVED = "CONNECT_APP_AUTH_CODE_RECEIVED";
export const CONNECT_APP_SUCCESS = "CONNECT_APP_SUCCESS";
export const CONNECT_APP_ERROR = "CONNECT_APP_ERROR";

export const APPLICATION_READY = "APPLICATION_READY";

export const ONBOARDING_NEXT = "ONBOARDING_NEXT";
export const ONBOARDING_PREVIOUS = "ONBOARDING_PREVIOUS";
export const ONBOARDING_FINISH = "ONBOARDING_FINISH";
export const GO_TO_VIEW = "GO_TO_VIEW";
export const OFFLINE = "OFFLINE";
export const ONLINE = "ONLINE";

export const OPEN_DETAILS_VIEW = "OPEN_DETAILS_VIEW";
export const DETAILS_READY = "DETAILS_READY";
export const HIDE_DETAILS_VIEW = "HIDE_DETAILS_VIEW";

export const OPEN_FULL_THREAD = "OPEN_FULL_THREAD";
